[package]
name = "mqtt-broker"
version.workspace = true
edition.workspace = true

[dependencies]
mqtt-core = { path = "../mqtt-core" }
tokio = { workspace = true }
tokio-util = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rusqlite = { workspace = true }

[lib]
name = "mqtt_broker"
path = "src/lib.rs"
